import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img src="" alt="" />
          <a href="/events">Events</a>
          <a href="/">Home</a>
          <a href="/about">About</a>
        </nav>
      </header>
      <main className={styles.main}>
        <h1>Events</h1>
        {data.map((ev) =>

          <a key={ev.id} href={`/events/${ev.id}`} >
            <h2>{ev.title}</h2>

            <Image src={ev.image} alt={ev.title} height={300} width={300} />
            <p>{ev.description}</p>



          </a>




        )}


      </main >
      <footer>
        2023
      </footer>
    </>
  )
}
export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json")

  return {
    props: {
      data: events_categories
    }
  }
}

